include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_print: true
    prefer_final_locals: true
    sort_constructors_first: true
    always_declare_return_types: true
    annotate_overrides: true
    avoid_empty_else: true
    prefer_single_quotes: true
